#1: Allow shortcuts to work inside input fields with flag
aurelia-contrib/aurelia-combo pull request #2
Opened 2020-04-08 16:28 UTC by zshall

* Disable the default filter that Keymaster uses, processing key commands on all keypresses.
* Changing the signature of `@combo()` to declare a list of shortcuts as a single parameter.
* Adding a second parameter, `runInsideInputs`, a flag to determine whether we should filter or not.
* Adding an `if` block inside the Keymaster handler to `return true` if we should be filtering inside inputs, and the default filter detects that we are currently in an input.

I added examples of both to the `dev-app`.

2020-04-08 16:43 UTC, zshall commented
I'm not familiar with the testing system used here and am not yet sure how to update the unit tests so that we can simulate focusing an input box. Looking into it now.

2020-04-08 20:23 UTC, zshall commented
I'm not sure how to proceed in testing this. Here's what I've tried:

I've added an HTML input `<input id="test-input" />` to line 44 in the spec file:

`@inlineView('<template><input id="test-input" /></template>')`

I've also added a test that is supposed to focus this test input and sends keys:

~~~js
      nq(() => {
        const testInput = document.getElementById('test-input');
        testInput.focus();
        // ctrl+f
        keydown(KEYS.ctrl); keydown(70, [KEYS.ctrl]); keyup(70); keyup(KEYS.ctrl);

        // no more trigger after focusing input
        expect(results).toEqual(['findIt', 'findIt', 'copyIt']);
      });
~~~

This doesn't seem to work, as the event is not being filtered out.

2020-04-08 21:41 UTC, 3cp requested changes

2020-04-08 21:41 UTC, 3cp commented on src/index.js
> +export function combo(shortcuts, runInsideInputs) {
This method signature change is a breaking change. Suggest to keep old signature, then check last param.

```js
combo(...shortcuts) {
  let runInsideInputs = false;
  if (shortcuts.length && typeof shortcuts[shortcuts.length - 1] === 'boolean') {
    runInsideInputs = shortcuts.pop();
  }
  //...
}
```

That will enable
```js
@combo('ctrl+f', 'command+f', true)
```

2020-04-08 21:41 UTC, 3cp commented on src/index.js
> +  key.filter = () => true; // disable Keymaster's built-in filter
Remove duplicated defaultKeymasterFilter, just get it from keymaster.

```js
const defaultKeymasterFilter = key.filter;
key.filter = () => true;
```

2020-04-08 21:41 UTC, 3cp commented on src/index.js
> +            return true;
This can be just `return;` I think.
The return value here is not used by aurelia.

2020-04-08 21:43 UTC, 3cp commented
Thx, I didn't realise is keymaster blocking the events.
For the tests, try a delay after focus.
```js
ng(() => do_focus);
ng(() => do_keypress...);
```

2020-04-08 21:44 UTC, 3cp commented on src/index.js
> +  key.filter = () => true; // disable Keymaster's built-in filter
Since we have local copy of keymaster, the other way we can clean it up is to totally remove filter from keymaster file, then use your code here.

2020-04-08 21:45 UTC, 3cp commented
If tests cannot work, just push them up. I will review in the long weekend.

2020-04-09 14:37 UTC, zshall commented
@3cp addressed your comments. Also figured out how to get the tests to work. `document` was the event target whenever the keys events were dispatched; now it's `document.activeElement`, so our `.focus()` calls work properly. Also used `ref` for the test input element so that we don't need to use `getElementById()`

2020-04-11 10:11 UTC, merged

2020-04-11 10:12 UTC, 3cp commented
Thx!

2020-04-11 10:24 UTC, 3cp commented
Released v1.1.0

2020-04-11 10:58 UTC, 3cp commented
I am using it. Love it!